#!/bin/sh

[ -f "$HOME/.xprofile" ] && . ~/.xprofile
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

source ~/.cache/wal/colors.sh

export color0_alpha="#22${color0/'#'}"
export color1_alpha="#22${color1/'#'}"
export color2_alpha="#22${color2/'#'}"
export color3_alpha="#22${color3/'#'}"
export color4_alpha="#22${color4/'#'}"
export color5_alpha="#22${color5/'#'}"

exec i3
