#!/bin/sh
ckb-next-daemon & #start corsair sw
setbg &		# Set the background
sxhkd &	# Bind keys
# Switch to US international with Caps as Mod/Escape
setxkbmap -option caps:super -variant altgr-intl && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xcompmgr &		# xcompmgr for transparency
dunstWal &			# dunst for notifications
mpdupdate &
redshift -t 6500:3000 -b 1.0:0.5 &
